# COINjecture Network B - Validator 3 Configuration
# Testnet Launch Configuration

[network]
chain_id = "coinject-testnet-b1"
data_dir = "./testnet/validator3/data"

[mining]
enabled = true
# Validator 3's address
miner_address = "0000000000000000000000000000000000000000000000000000000000000003"

[consensus]
difficulty = 2
block_time = 30

[p2p]
# Validator 3 listens on different port
listen_addr = "/ip4/0.0.0.0/tcp/30335"
# Bootstrap from both validator 1 and 2
bootnodes = [
    "/ip4/127.0.0.1/tcp/30333/p2p/PEER_ID_1",
    "/ip4/127.0.0.1/tcp/30334/p2p/PEER_ID_2"
]

[rpc]
listen_addr = "127.0.0.1:9935"
enabled = true

[logging]
level = "info"
